## Site Meta ##
# The title of the website.
title: "呆呆的幸福生活"
# The description of the website
description: "一个关于呆呆的图片博客。"
# Keywords/tags for you site.
keywords: "lens, jeykll-lens, jekyll, theme, jekyll-theme, photography, blog, photography-blog, photo-blog"
# Your copyright message.
copyright: "Copyright &copy; 2026 - lengdp."

## Site Configurations ##
# 1st heading of the site.
header: "呆呆"
# 2nd heading/sub heading of the website.
subheader: "的幸福生活"
# A description/bio of the website.
bio: "一个关于呆呆的图片博客。"
social:
  # Your Twitter username.
  twitter_username: ""
  # Your Facebook username.
  facebook_username: ""
  # Your Instagram username.
  instagram_username: ""
  # GitHub username.
  github_username: "ElasticDesigns"
  # Your email address.
  email: ""

## Gallery Configuration ##
# If you modify this, also modify the `default.scope.path` key below.
gallery_dir: "gallery"
# Any valid value of "background-position" CSS attribute.
image_position: "left center"

## Jekyll Configuration ##
defaults:
 - scope:
    # Should be same as the `gallery_dir` key above.
    path: "gallery"
   values:
    image: true
